#copy this to the same folder as match.sh and run sh match.sh
#!/usr/bin/perl

open OPEN, "<MYC_AllElements_hU6_Scaffold.tsv" or die "dead";
while (<OPEN>) {
  die unless /(MYC\-hU6\@\d+)\s+ATATCTTGTGGAAAGGACGAAACACC(G[ACTG]{19,20})GTTTTAGAGCTAGAAATAGCAAGTTAAAATAAGGC/;
  ($id, $gRNA)=($1,$2);
  $SRC{$gRNA}=$id;
}

while (<>) {
  die "?$_" unless /^[ACTGN]+$/;
  $TOTAL++;
  next unless /CACC(G[ACTG]{19,20})GTT/;
  $gRNA=$1; $FOUND++;
  next unless exists $SRC{$gRNA};
  $MATCH++;
  $CNT{$gRNA}++;
  #print if exists $SRC{$gRNA}; 
}

$UNIQ=keys %CNT;
print "$TOTAL\t$FOUND\t$MATCH\t$UNIQ\n";

foreach (keys %CNT) {
  print "$_\t$SRC{$_}\t$CNT{$_}\n";
}

__END__
Dppa2-hU6@00001	CTTGTGGAAAGGACGAAACACCGAGCTGGGAGATGGGTCAAATGTTTTAGAGCTAGAAATAGCAAGTTAAAAT
Dppa2-hU6@00002	CTTGTGGAAAGGACGAAACACCGACTGCGGGAGCAGCAGGCAGGTTTTAGAGCTAGAAATAGCAAGTTAAAAT
Dppa2-hU6@00003	CTTGTGGAAAGGACGAAACACCGACTGCGGGAGCAGCAGGCAGTTTTAGAGCTAGAAATAGCAAGTTAAAAT
Dppa2-hU6@00004	CTTGTGGAAAGGACGAAACACCGGACTGCGGGAGCAGCAGGCGTTTTAGAGCTAGAAATAGCAAGTTAAAAT
Dppa2-hU6@00005	CTTGTGGAAAGGACGAAACACCGTGGGGACTGCGGGAGCAGCGTTTTAGAGCTAGAAATAGCAAGTTAAAAT
Dppa2-hU6@00006	CTTGTGGAAAGGACGAAACACCGCGAAGAGGGTGGGGACTGCGTTTTAGAGCTAGAAATAGCAAGTTAAAAT
Dppa2-hU6@00007	CTTGTGGAAAGGACGAAACACCGTGGCAAGGCGAAGAGGGTGGTTTTAGAGCTAGAAATAGCAAGTTAAAAT
Dppa2-hU6@00008	CTTGTGGAAAGGACGAAACACCGAGTGGCAAGGCGAAGAGGGTGTTTTAGAGCTAGAAATAGCAAGTTAAAAT
Dppa2-hU6@00009	CTTGTGGAAAGGACGAAACACCGCAGTGGCAAGGCGAAGAGGGGTTTTAGAGCTAGAAATAGCAAGTTAAAAT
Dppa2-hU6@00010	CTTGTGGAAAGGACGAAACACCGTCTCAGTGGCAAGGCGAAGAGTTTTAGAGCTAGAAATAGCAAGTTAAAAT
